### ISSUE TITLE
Using mutexes in C primitives is dodgy

### ISSUE THREAD

**Issue by stedolan** [ocaml-multicore/ocaml-multicore#114]
It's bad to hold a mutex across arbitrary user code. Because of signal handlers and finalisers, almost anything in the C runtime runs arbitrary user code. So, it's bad to hold mutexes in C primitives (!).

The primitives in io.c do this. Are they broken? Are they broken in stock OCaml?

To avoid this, we need to either:
  1. never hold mutexes across runtime functions
  2. never run arbitrary callbacks (signals, finalisers, etc.) during runtime functions

Which makes more sense?

**Comment by stedolan** [comment]
turns out it's broken in stock OCaml

https://caml.inria.fr/mantis/view.php?id=7503

https://github.com/ocaml/ocaml/pull/1128

**Comment by mrvn** [comment]
Mutexes should be held for the minimum amount of time to avoid congestion. Clearly running arbitrary user code will add an unknown amount (even infinite for deadlocks) of delay before the mutex is freed.

I think option 1 is better but option 2 might be necessary in select cases.

**Comment by stedolan** [comment]
I agree that 1 is definitely better.

**Comment by kayceesrk** [comment]
This has been fixed by https://github.com/ocaml/ocaml/pull/9722, but the port needs to be merged into multicore. I'll close this issue as the fix will be incorporated when upstream changes are merged into multicore next.
