### ISSUE TITLE
Continuation patterns are too strict

### ISSUE THREAD

**Issue by stedolan** [ocaml-multicore/ocaml-multicore#126]
Currently, in the syntax for handling effects `effect Epat Kpat`, only variables and `_` are allowed as the pattern to match a continuation.

I think e.g. `(k : (unit, int) continuation)` should also be allowed, since it can be useful to be explicit about the type of the continuation.

(This might be a good first task for someone who wants to explore the type checker)

Here's an example program that should work but doesn't:
```
effect E : int
let run f =
  match f () with
  | s ->
     print_string s
  | effect E (k : (int, string) continuation) ->
     continue k 42
```

**Comment by vramana** [comment]
Is this a Good First Task for people who have already contributed to OCaml compiler? Or Is is possible to work on this issue having no experience contributing to OCaml compiler?

**Comment by stedolan** [comment]
I think this would be a good first task regardless of experience. However, if you haven't touched the compiler before it may take a while to learn how things are layed out!
