### ISSUE TITLE
Effects and caml_callback

### ISSUE THREAD

**Issue by stedolan** [ocaml-multicore/ocaml-multicore#146]
Currently, performing an effect doesn't work from within caml_callback (that is, when C code has called OCaml code). The tricky thing is managing the C state - we don't manage the C stack, so the stack-switching we do for effects isn't enough to pause and resume C functions.

Instead, we could use multiple C threads to have the operating system provide multiple C stacks, and switch between those.

**Comment by kayceesrk** [comment]
The idea is to introduce a new attribute for external calls `@@performseffects` which means that the external call or its children (including any callbacks into OCaml) may perform effects that escape. Our goal is to ensure that C frames belonging to two different logical stacks don't end up on the same C stack.

Before calling such function, if there is a handler currently installed on the stack, then we instantiate a new C thread and make the function call in the new C thread. The old C thread is suspended on a condition variable waiting to be resumed. If this function performs an effect, whose handler is in the old C stack, we suspend the current C thread and switch to the old C thread. Any subsequent external calls performed by the handler computation (which are not marked with @@performseffects) will end up on the old C stack. Subsequently on resuming the continuation, we switch back to the new C thread through the condition variable mechanism. 

In this scheme, the penalty of switching C threads is paid only when performing effects whose continuations may capture C frames. Similar ideas were presented in the paper [Threads Yield Continuations](https://www.cs.indiana.edu/~dyb/pubs/LaSC-10-3-pp223-236.pdf).

**Comment by rbjorklin** [comment]
I'm taking a peek at this project every now and then and just noticed that b6d624f was merged a couple of days back. Does that commit bring this any closer to being complete?
