### ISSUE TITLE
building merlin with ocaml-multicore fails

### ISSUE THREAD

**Issue by mprevot** [ocaml-multicore/ocaml-multicore#189]
After installing ocaml-multicore with opam, I'm installing merlin but it fails with a file that is I think specific to ocaml-multicore.

How to solve this ?

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[biniou.1.2.0] found in cache
[cppo.1.6.4] found in cache
[easy-format.1.3.1] found in cache
[jbuilder.1.0+beta20] found in cache
[merlin.3.0.5] found in cache
[ocamlfind.1.8.0] found in cache
[yojson.1.4.1] found in cache

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
∗ installed conf-m4.1
∗ installed conf-which.1
∗ installed jbuilder.1.0+beta20
∗ installed easy-format.1.3.1
∗ installed biniou.1.2.0
∗ installed ocamlfind.1.8.0
∗ installed base-bytes.base
∗ installed cppo.1.6.4
∗ installed yojson.1.4.1
[ERROR] The compilation of merlin failed at "/home/mprevot/.opam/opam-init/hooks/sandbox.sh build make -j 1".

=== ERROR while compiling merlin.3.0.5 =======================================#
 context     2.0.0~rc2 | linux/x86_64 | ocaml-variants.4.06.1+multicore | https://opam.ocaml.org/2.0#b36f28db
 path        ~/.opam/4.06.1+multicore/.opam-switch/build/merlin.3.0.5
 command     ~/.opam/opam-init/hooks/sandbox.sh build make -j 1
 exit-code   2
 env-file    ~/.opam/log/merlin-81501-1a5911.env
 output-file ~/.opam/log/merlin-81501-1a5911.out
## output ###
 [...]
 /home/mprevot/.opam/4.06.1+multicore/lib/ocaml/caml/domain_state.h:17:10: fatal error: domain_state.tbl: No such file or directory
  #include "domain_state.tbl"
           ^~~~~~~~~~~~~~~~~~
 compilation terminated.
 OCamlMakefile:1135: recipe for target 'src/platform/platform_misc.o' failed
 make[2]: *** [src/platform/platform_misc.o] Error 2
 make[2]: Leaving directory '/home/mprevot/.opam/4.06.1+multicore/.opam-switch/build/merlin.3.0.5'
 OCamlMakefile:780: recipe for target 'native-code' failed
 make[1]: *** [native-code] Error 2
 make[1]: Leaving directory '/home/mprevot/.opam/4.06.1+multicore/.opam-switch/build/merlin.3.0.5'
 Makefile:56: recipe for target 'ocamlmerlin-server' failed
 make: *** [ocamlmerlin-server] Error 2

**Comment by kayceesrk** [comment]
Hi @mprevot.

> /home/mprevot/.opam/4.06.1+multicore/lib/ocaml/caml/domain_state.h:17:10: fatal error: domain_state.tbl: No such file or directory
> #include "domain_state.tbl"

This was fixed by https://github.com/ocamllabs/ocaml-multicore/commit/a9b04c2d8106c5b9a30c7364d57b0aad6961293d, but hasn't been included in the 4.06.1+multicore switch. You can install the trunk version of the multicore compiler which fixes this:

```bash
$ opam remote add multicore https://github.com/ocamllabs/multicore-opam.git
$ opam switch 4.06.1+multicore+trunk
```

[0] https://github.com/ocamllabs/multicore-opam

**Comment by mprevot** [comment]
@kayceesrk  thanks for the details. merlin was successfully built and installed.

However, I later run into other problems:

> let log = Printf.printf
> 
> let rec f id depth =
>   log "Starting number %i\n%!" id;
>   if depth > 0 then begin
>     log "Forking number %i\n%!" (id * 2 + 1);
>     Sched.fork (fun () -> f (id * 2 + 1) (depth - 1));
>     log "Forking number %i\n%!" (id * 2 + 2);
>     Sched.fork (fun () -> f (id * 2 + 2) (depth - 1))
>   end else begin
>     log "Yielding in number %i\n%!" id;
>     Sched.yield ();
>     log "Resumed number %i\n%!" id;
>   end;
>   log "Finishing number %i\n%!" id
> 
> let () = Sched.run (fun () -> f 0 2)

I got:

> ocamlopt -g pa.ml -o pa
> File "pa.ml", line 7, characters 4-14:
> Error: Unbound module Sched
> Makefile:6: recipe for target 'all' failed
> make: *** [all] Error 2

**Comment by mprevot** [comment]
Thanks, I managed to have it compile and work: great.
However, I have an error that was not showing without multicore, in merlin I'm not sure if it's related to multicore or merlin:

merlin:

> This expression has type string/15
>        but an expression was expected of type string/17
> string/17 is abstract because no corresponding cmi file was found in path.

I'm using this command `ocamlopt -g pa.ml -o pa` and this code:

```
let log = Printf.printf

let rec f id depth =
  log "Starting number %i\n%!" id; # <- HERE
  if depth > 0 then begin
    log "Forking number %i\n%!" (id * 2 + 1);
    Sched.fork (fun () -> f (id * 2 + 1) (depth - 1));
    log "Forking number %i\n%!" (id * 2 + 2);
    Sched.fork (fun () -> f (id * 2 + 2) (depth - 1))
  end else begin
    log "Yielding in number %i\n%!" id;
    Sched.yield ();
    log "Resumed number %i\n%!" id;
  end;
  log "Finishing number %i\n%!" id

let () = Sched.run (fun () -> f 0 2)
```

but this happens also with all `printf "some text"`.

**Comment by kayceesrk** [comment]
Probably an incompatibility w/ multicore and merlin due to the new syntax extensions in multicore. I am not sure what the error is. Best to ask merlin folks about this.

**Comment by mprevot** [comment]
If you want to follow: [merlin/issues/823](https://github.com/ocaml/merlin/issues/823).
I think it would be useful to integrate the new syntax.
If merlin guys don't feel available for this task, it might be a good thing to fork merlin and have this version support the new grammar. It doesn't look too complex.

**Comment by trefis** [comment]
FTR I don't see any new syntax in there; assuming merlin can read the `.cmi` files produced by multicore (which is not obvious, given well... effects) then this should work fine.

**Comment by Sudha247** [comment]
This issue is old, we have a version of merlin working with `4.10.0+multicore` now. It can be installed via [multicore-opam](https://github.com/ocaml-multicore/multicore-opam). As of now, merlin in multicore-opam doesn't work with `4.12` because a dependency requires the OCaml version to be 4.11 or lesser. Any updates on this will be up on multicore-opam.

I'm closing this one since there's a working version, you're welcome to report any other issues with merlin.
