### ISSUE TITLE
Random question - libuv

### ISSUE THREAD

**Issue by ORESoftware** [ocaml-multicore/ocaml-multicore#229]
I am following the concurrency advancments in OCaml closely, including this one:

https://github.com/fdopen/uwt

Coming from Node.js, I was really interested in whether OCaml could leverage async I/O and base its concurrency model around that.

My question is - is there room for both this multicore project and libuv? Would they complement each other or would they be used in different areas?

**Comment by stedolan** [comment]
Yes, definitely. The advantage of effects here is that the system can use async I/O internally without the user having to structure all code as callbacks.

There's a prototype of multicore async IO living at https://github.com/kayceesrk/ocaml-aeio (although not using libuv). We haven't finishing evaluating libuv vs. alternatives yet, so I'm not sure what the underlying IO library will be.
