### ISSUE TITLE
OCaml 4.06.1+multicore cannot build Dune >= 1.4

### ISSUE THREAD

**Issue by jhwoodyatt** [ocaml-multicore/ocaml-multicore#234]
OCaml 4.06.1+multicore fails to compile Dune 1.8.2 (and probably most other versions going back to the 1.3 series). This problem stems from a variety of contributing factors, all noted here in this report.

Firstly, Dune is using fairly extensively the `Thread` library, which is not yet supported on multicore (Issue #100). Secondly, it uses `Unix.fork` followed by `Unix.execvpe` rather than `Unix.create_process_env`, which would prevent it from working even with a working approximation of system threads built on the `Domain` library (Issue #81). Finally, even `Unix.create_process_env` (and its various cognates) are implemented internally in terms of `Unix.fork` and the various `Unix.execvxyz` functions, so Dune would likely remain broken for Multicore OCaml unless something happens in the `Unix` library to improve the situation.

In any case, it's probably worth tracking the problem here.

**Comment by jhwoodyatt** [comment]
I have written a patch for the `Unix` library that dispatches the `create_process_xxx` and `open_process_xxx` functions to external C language primitives that call `fork` and the appropriate `execvxyz` system call in a single departure from the OCaml critical section. I would file a pull request if invited to do so. The branch is [here](/jhwoodyatt/ocaml-multicore/tree/x-create-process).

**Comment by jhwoodyatt** [comment]
Pull requests #240 and #241 are candidates for addressing this issue.

**Comment by kayceesrk** [comment]
Closing this issue as the work has now evolved into #381.
