### ISSUE TITLE
Blocking issues for systhreads support

### ISSUE THREAD

**Issue by kayceesrk** [ocaml-multicore/ocaml-multicore#239]
Ugh. So there are multiple things blocking me now.

1. The `fileio` test calls `Unix.system` which is implemented in terms of `Unix.fork` so that fails just because my tactic of using a domain per thread means the fork isn't allowed. I posted that other patch that reimplements all those functions without using `Unix.fork`, but who knows what will ever become of that.
2. The `pr5325` test is deadlocking. Not sure why. Investigation reveals that something somewhere inside the multicore platform does not like `Domain.Sync.wait_until` when there is only one other domain and it's blocked in a system call. It can decide for reasons I don't fully understand that it needs to go do a GC major slice, and that blocks on the platform lock somehow.

I'm gonna post my unfinished [branch](/jhwoodyatt/ocaml-multicore/tree/x-dthreads) to my account and go do other things for a while.

_Originally posted by @jhwoodyatt in https://github.com/ocaml-multicore/ocaml-multicore/issues/100#issuecomment-478296502_

**Comment by jhwoodyatt** [comment]
I have filed #240 to help with analysis of this problem.

**Comment by ctk21** [comment]
#381 implements systhreads as pthreads within a domain and the problems described with `fileio` and `pr5325` are solved.
