### ISSUE TITLE
Auto healing

### ISSUE THREAD

**Issue by ShalokShalom** [ocaml-multicore/ocaml-multicore#242]
Hi there :)

Today, a friend told me that multicore OCaml can implement in theory some auto healing capabilitys, similar to Erlangs let-it-crash philosophy. 

He added, that this is currently only the case on the user level, so will this repo implement such a functionality in the language itself, or is a library in your vision, alternatively?

**Comment by stedolan** [comment]
Are you talking about erlang/OTP supervisors? This should be possible, implemented as a library (as it is in erlang/OTP, IIRC).

**Comment by ShalokShalom** [comment]
Yes, I mean so
