### ISSUE TITLE
ctypes opam package fails with multicore

### ISSUE THREAD

**Issue by ctk21** [ocaml-multicore/ocaml-multicore#245]
Can recreate by running sandmark against a multicore compiler (it prevents the following sandmark benchmarks from running frama-c and js_of_ocaml (which uses frama-c.byte as input)).

Error I see is this:
```
# /local/scratch/ctk21/sm_mc_backfill/6de883c0721e5bbfd5af4a502aad2e2d799742d9/sandmark/_opam/4.06.1+multicore/.opam-switch/build/ctypes.0.14.0/src/ctypes/ctypes_roots.c:33:3: warning: implicit declaration of function 'caml_remove_generational_global_root'; did you mean 'remove_global_root'? [-Wimplicit-function-declaration]
# [...]
#    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#    remove_global_root
# cd _build/src/ctypes && ocamlfind  ocamlc -c -package bigarray -package bytes -package integers   -ccopt -fPIC -ccopt -Wall -ccopt -g -ccopt "-I/local/scratch/ctk21/sm_mc_backfill/6de883c0721e5bbfd5af4a502aad2e2d799742d9/sandmark/_opam/4.06.1+multicore/lib/integers" -ccopt -I -ccopt /local/scratch/ctk21/sm_mc_backfill/6de883c0721e5bbfd5af4a502aad2e2d799742d9/sandmark/_opam/4.06.1+multicore/.o[...]
# /local/scratch/ctk21/sm_mc_backfill/6de883c0721e5bbfd5af4a502aad2e2d799742d9/sandmark/_opam/4.06.1+multicore/.opam-switch/build/ctypes.0.14.0/src/ctypes/ldouble_stubs.c: In function 'ldouble_cmp':
# /local/scratch/ctk21/sm_mc_backfill/6de883c0721e5bbfd5af4a502aad2e2d799742d9/sandmark/_opam/4.06.1+multicore/.opam-switch/build/ctypes.0.14.0/src/ctypes/ldouble_stubs.c:85:5: error: 'caml_compare_unordered' undeclared (first use in this function); did you mean 'caml_copy_double'?
#      caml_compare_unordered = 1;
#      ^~~~~~~~~~~~~~~~~~~~~~
#      caml_copy_double
# /local/scratch/ctk21/sm_mc_backfill/6de883c0721e5bbfd5af4a502aad2e2d799742d9/sandmark/_opam/4.06.1+multicore/.opam-switch/build/ctypes.0.14.0/src/ctypes/ldouble_stubs.c:85:5: note: each undeclared identifier is reported only once for each function it appears in
# Makefile.rules:116: recipe for target '_build/src/ctypes/ldouble_stubs.o' failed
# make: *** [_build/src/ctypes/ldouble_stubs.o] Error 2
```

The `caml_compare_unordered` looks like a global not being handled the multicore conversion tool, but likely more than that.

**Comment by yallop** [comment]
The released ctypes probably won't work with multicore OCaml, but there's a branch here with some changes for the new API:

https://github.com/yallop/ocaml-ctypes/tree/multicore-api

The latest commit on the branch looks like a fix for the `caml_compare_unordered` error above:

> [Add a declaration for caml_compare_unordered](https://github.com/yallop/ocaml-ctypes/commit/14d0e913e82f8de2ecf739970561066b2dce70b7)
> ```diff
> diff --git a/src/ctypes/ldouble_stubs.c b/src/ctypes/ldouble_stubs.c
> index c625e441..70faad2b 100644
> --- a/src/ctypes/ldouble_stubs.c
> +++ b/src/ctypes/ldouble_stubs.c
> @@ -78,6 +78,8 @@ static long double norm(long double x) {
>    }
>  }
>  
> +extern int caml_compare_unordered;
> +
>  static int ldouble_cmp(long double u1, long double u2) {
>    if (u1 < u2) return -1;
>    if (u1 > u2) return 1;
>

**Comment by ctk21** [comment]
Using the ctypes commit above for multicore gets it installing. I did this by altering the url for the ctypes opam config in sandmark to use:
  https://github.com/yallop/ocaml-ctypes/archive/14d0e913e82f8de2ecf739970561066b2dce70b7.tar.gz
(I can't see an easy way to switch url within opam dependent on the compiler variant)

I'll close this out and add some documentation to sandmark so others can get going. 

Thanks!
