### ISSUE TITLE
Multicore microbenchmark regressions

### ISSUE THREAD

**Issue by kayceesrk** [ocaml-multicore/ocaml-multicore#250]
[bench.ocamllabs.io](http://bench.ocamllabs.io/comparison/?exe=6%2BL%2Bmaster&ben=1%2C2%2C110%2C111%2C5%2C6%2C7%2C9%2C8%2C10%2C12%2C11%2C15%2C16%2C17%2C13%2C14%2C20%2C21%2C22%2C18%2C19%2C25%2C26%2C27%2C23%2C24%2C30%2C31%2C32%2C28%2C29%2C33%2C152%2C151%2C37%2C112%2C113%2C114%2C115%2C116%2C117%2C118%2C119%2C120%2C122%2C121%2C123%2C124%2C125%2C126%2C127%2C54%2C154%2C155%2C153%2C157%2C158%2C156%2C161%2C162%2C163%2C164%2C159%2C160%2C167%2C168%2C169%2C170%2C165%2C166%2C172%2C171%2C174%2C173%2C86&env=2&hor=true&bas=5%2BL%2B4.06&chart=normal+bars) comparion between vanilla and multicore shows that multicore is slower on a number of micro-benchmarks. Need to investigate the regressions.

**Comment by ctk21** [comment]
A chunk of changes and improvements have been done in Q1 2020 to address multicore performance.
