### ISSUE TITLE
Failed assertion with atomics containing block values

### ISSUE THREAD

**Issue by gmevel** [ocaml-multicore/ocaml-multicore#252]
I ran into segmentation faults while overwriting atomic cells containing option values. The optional value was sometimes corrupted, leading in my case to random integers, or invalid pointers.

A minimal example:
```ocaml
type u = U of unit

let make_cell (x : unit) : u Atomic.t =
  let cell = Atomic.make (U x) in
  Atomic.set cell (U x) ;
  cell

(* the error shows up with an array of length 256 or larger *)
let a = Array.make 256 (make_cell ())
```

This code itself is not apparently failing, but compiling and running it in debug mode:

```sh
ocamlc test.ml -o test.byte && ocamlrund test.byte
```

reveals a failed assertion:

```
### OCaml runtime: debug mode ###
[00] file minor_gc.c; line 555 ### Assertion failed: caml_addrmap_contains(&young_young_ptrs, (value)f)
Abandon (core dumped)
```

In case it matters:

 *  architecture = x86_64
 *  operating system = Linux 5.1.5-arch1-2-ARCH
 *  compiler = Multicore OCaml 4.06.1 (from the opam switch)

**Comment by stedolan** [comment]
Thanks for the report! This looks like a mistake in `caml_atomic_exchange`, where the write barrier should be called but is not.
