### ISSUE TITLE
'PTHREAD_MUTEX_ERRORCHECK_NP' undeclared

### ISSUE THREAD

**Issue by bornej** [ocaml-multicore/ocaml-multicore#266]
Hi, i'm trying to build ocaml-multicore on alpine linux, which relies 
on musl libc rather than the glibc. 

```

# gcc -c -O2 -fno-strict-aliasing -fwrapv -Wall -fno-tree-vrp  -g -D_FILE$
# gcc -c -O2 -fno-strict-aliasing -fwrapv -Wall -fno-tree-vrp  -g -D_FILE$
# gcc -c -O2 -fno-strict-aliasing -fwrapv -Wall -fno-tree-vrp  -g -D_FILE$
# platform.c: In function 'caml_plat_mutex_init':
# platform.c:25:34: error: 'PTHREAD_MUTEX_ERRORCHECK_NP' undeclared (firs$
#    pthread_mutexattr_settype(&ma, PTHREAD_MUTEX_ERRORCHECK_NP);
#                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
#                                   PTHREAD_MUTEX_ERRORCHECK

```
Understandably gcc complains it cannot find the non-portable version
`PTHREAD_MUTEX_ERRORCHECK_NP`

I understand what `PTHREAD_MUTEX_ERRORCHECK` does ([Posix manual](http://man7.org/linux/man-pages/man3/pthread_mutex_lock.3p.html))

But I am not sure about `PTHREAD_MUTEX_ERRORCHECK_NP`.
I Couldn't find much information... 
I tried to have a look into glibc source, 
found something about not doing lock elision, ...

Could someone help me understand what `PTHREAD_MUTEX_ERRORCHECK_NP` does?

Also, in `platform.c`, should I simply discard 
`#define _GNU_SOURCE /* for PTHREAD_MUTEX_ERRORCHECK_NP */`
and use the standard `PTHREAD_MUTEX_ERRORCHECK` ?

I was able to build successfully doing so but I suspect the `_NP` was here for a reason...

**Comment by XVilka** [comment]
`_NP` suffix means "non-portable", thus definitely should not be used. Some of the C libraries support `_NP` functions too, e.g. uclibc:
 https://github.com/kraj/uClibc/blob/master/libpthread/linuxthreads/sysdeps/pthread/pthread.h#L87
