### ISSUE TITLE
DWARF fix for fast native calls is not quite right

### ISSUE THREAD

**Issue by kayceesrk** [ocaml-multicore/ocaml-multicore#274]
PR ~#271~ #272 is not quite right. @sadiqj reported observing backtraces that terminate at `caml_c_call`. This is unsurprising as the current fix seems simpler than the corresponding code in https://github.com/ocaml-multicore/ocaml-multicore/blob/master/asmrun/amd64.S#L150-L152.

**Comment by ctk21** [comment]
I've been poking around and the backtraces are definitely broken. It is a bit more apparent with this testcase:
```ocaml
let hello () =
  print_string "Hello, world!\n"

let foo () =
  let x = log1p 2.0 in
  Printf.printf "x=%f\n" x

let _ =
  hello ();
  foo ()
```
With a breakpoint at `caml_log1p` I get the following broken backtrace in gdb:
<pre>
(gdb) bt
#0  caml_log1p (x=2) at floats.c:900
#1  0x000055555558e88a in camlFoo2__foo_85 ()
#2  &ltsignal handler called&gt
<b>#3  0x0000555555590678 in camlStdlib__output_string_265 () at stdlib.ml:380</b>
#4  0x000055555558e998 in camlFoo2__entry ()
#5  0x000055555558ba84 in caml_program ()
#6  &ltsignal handler called&gt
#7  caml_startup_common (argv=0x7fffffffe538, pooling=<optimised out>, pooling@entry=0) at startup_nat.c:139
#8  0x00005555555d2a48 in caml_startup_exn (argv=<optimised out>) at startup_nat.c:143
#9  caml_main (argv=<optimised out>) at startup_nat.c:148
#10 0x000055555558b86c in main (argc=<optimised out>, argv=<optimised out>) at main.c:44
</pre>

`camlStdlib__output_string_265` is certainly bogus.
