### ISSUE TITLE
Flambda support for effect handlers

### ISSUE THREAD

**Issue by kayceesrk** [ocaml-multicore/ocaml-multicore#327]
Effect handlers add [new primitives to lambda intermediate language](https://github.com/ocaml-multicore/ocaml-multicore/blob/parallel_minor_gc/bytecomp/lambda.mli#L77-L81), which are [compiled to external calls during closure conversion](https://github.com/ocaml-multicore/ocaml-multicore/blob/parallel_minor_gc/asmcomp/closure.ml#L1016-L1034). In order to get Multicore OCaml to use flambda optimisation passes, we need corresponding changes in [flambda closure conversion](https://github.com/ocaml-multicore/ocaml-multicore/blob/parallel_minor_gc/middle_end/closure_conversion.ml).

**Comment by lpw25** [comment]
I think that you should move the translation of the primitives from `closure.ml` to `cmmgen.ml`. That is where most primitives are translated and it works for both flambda and non-flambda compilers.

**Comment by kayceesrk** [comment]
PR #328 fixes this.

**Comment by kayceesrk** [comment]
Fixed by #328.
