### ISSUE TITLE
`Unhandled` exception should print the effect name

### ISSUE THREAD

**Issue by kayceesrk** [ocaml-multicore/ocaml-multicore#33]
```
# effect E : int -> unit;;
effect E : int -> unit
# perform (E 0);;
Exception: Unhandled.
```

Currently, unhandled effects raise `Unhandled` exception at the top level. It would be useful to change `exception Unhandled` to `exception Unhandled of string` where the exception is parameterized with the unhandled effect name.

**Comment by lpw25** [comment]
I think we should go a step further and use:

```ocaml
exception Unhandled : 'a eff -> exn
```

including the actual effect in the exception. We should also make sure the default top-level printer is able to print this as something like `Uncaught exception Unhandled(Foo(_))`.
