### ISSUE TITLE
ocamldebug

### ISSUE THREAD

**Issue by stedolan** [ocaml-multicore/ocaml-multicore#34]
The bytecode ocaml debugger does not know about effects or multiple stacks.

**Comment by kayceesrk** [comment]
As you'd mentioned in a separate conversation, `ocamldebug` cannot be quite made to work with multicore since it relies on `fork` which doesn't play well with system threads. The alternative perhaps is to get `ocamldebug` to just work for single core and raise an error under multicore execution.

**Comment by kayceesrk** [comment]
We now have `caml_domain_alone` which can be used to check whether the current domain is the only domain that is active (including domains blocked on external calls).
