### ISSUE TITLE
Unix.fork

### ISSUE THREAD

**Issue by stedolan** [ocaml-multicore/ocaml-multicore#81]
Forking is a disaster in any threaded program, but we'll need to support at least simple uses of `Unix.fork`.

At first, we should just throw an exception if more than one domain is running when `Unix.fork` is called. After the fork, the child will need to reinitialise mutexes (e.g. using `pthread_atfork`), in order to continue running caml code.

**Comment by stedolan** [comment]
Tentative fix in a04d3e02410aa6b51d5dd7d0b42eb1ae14dcac55, which allows forking when there is only one domain.

It relies on initialised unlocked pthread mutexes remaining so after a fork. I'm not sure whether this is reliable on all platforms.

Also, while `Unix.fork` is dodgy with multiple domains, `Unix.create_process` is very sensible. Since it's currently implemented in terms of `fork`, it will break at the moment when multiple domains are running.

**Comment by DemiMarie** [comment]
GHC handles this differently: it includes dedicated support in the runtime system for forking runtime safely.

**Comment by stedolan** [comment]
@DemiMarie Do you have a reference for that? All I could find was [`System.Posix.Process.forkProcess`](https://downloads.haskell.org/~ghc/7.0.4/docs/html/libraries/unix-2.4.2.0/System-Posix-Process.html#g:2), which has the same single-thread restriction as here.

**Comment by stedolan** [comment]
@DemiMarie Do you have a reference for that? I can't find much information about the semantics of `fork` in multithreaded haskell programs.

**Comment by kayceesrk** [comment]
@DemiMarie The documentation seems to indicate that GHC's fork has the same semantics: https://downloads.haskell.org/~ghc/7.0.4/docs/html/libraries/unix-2.4.2.0/System-Posix-Process.html#g:2.

**Comment by DemiMarie** [comment]
@kayceesrk That documentation is for an old version.  The [current docs] mention no such limitations, and indeed forking does work on a GHCi with multiple cores in use.

[current docs]: https://downloads.haskell.org/~ghc/latest/docs/html/libraries/unix-2.7.2.0/System-Posix-Process.html

**Comment by kayceesrk** [comment]
Thanks @DemiMarie! The new version seems to be an improvement; while other threads are not copied, `forkProcess` is possible in the presence of multiple threads.

**Comment by ctk21** [comment]
This issue is old. We've got a working `fork` implementation along the lines of:

> At first, we should just throw an exception if more than one domain is running when Unix.fork is  called. After the fork, the child will need to reinitialise mutexes (e.g. using pthread_atfork), in order to continue running caml code.

Closing it out. If there are remaining fork issues, then people can file new issues.
