### ISSUE TITLE
Native i386 port

### ISSUE THREAD

**Issue by kayceesrk** [ocaml-multicore/ocaml-multicore#87]
Implement `i386` backend for multicore. See https://github.com/ocamllabs/ocaml-multicore/issues/86 for details.

**Comment by ShalokShalom** [comment]
Why this?

**Comment by db4** [comment]
@kayceesrk, amd64 backend holds pointer to the domain state block in r15. Do you think that x86 backend should also use dedicated general-purpose register (like ebp) for that? Number of x86 registers is quite limited, won't this affect performance? Or maybe use SSE xmm0 register as a pointer?

@ShalokShalom are you against x86 port in general or you just think that this task is not for beta version?

**Comment by ShalokShalom** [comment]
I am simply interested in the background. 
How many multicore 32 Bit devices exist?

So it is for 64 Bit CPUs and you think it can result in lower RAM usage?

**Comment by db4** [comment]
> How many multicore 32 Bit devices exist?

Yes, all modern CPUs are 64-bit. But I need multicore under Windows so x86 backend is a must for me. Windows x86 is still very wide-spread to drop its support right now.

**Comment by ShalokShalom** [comment]
Ah, I see.

**Comment by kayceesrk** [comment]
> amd64 backend holds pointer to the domain state block in r15. Do you think that x86 backend should also use dedicated general-purpose register (like ebp) for that? Number of x86 registers is quite limited, won't this affect performance? Or maybe use SSE xmm0 register as a pointer?

r15 is the allocation pointer and we perform some bittwiddling to get the domain state just before the minor heap of a particular domain. So we don't use more registers than what is already used in amd64. That said, we are planning to steal r14 for domain state (currently this holds the exception pointer). This should make the design much simpler. We don't foresee any impact for installing trap frames and throwing exceptions (if any should be minimal [to be evaluated]). This change will also make allocations faster as we will not need to read global variables for minor heap limits; it will be at a known location at a fixed offset from r14. Again, this change shouldn't consume more registers on x86 than currently used.

**Comment by db4** [comment]
@kayceesrk Probably I was not clear enough, sorry for that. By `x86` I meant `i386` port that does not exist yet. Where would you like to hold domain state pointer for `i386` port if one would try to implement it? `ebp`? `xmm0`? something else?

**Comment by bluddy** [comment]
@db4 since there aren't enough registers in i386, the pointer will have to be a value in thread-based local storage, similar to what's done in bytecode. This is similar to the current runtime, which stores the allocation bump pointer and exception pointer in globals for i386. Notably, since 32 bit code needs to deal with a lot less memory at all times, it often makes up for the performance difference of having fewer registers.

**Comment by db4** [comment]
> since there aren't enough registers in i386, the pointer will have to be a value in thread-based local storage, similar to what's done in bytecode.

OK, but it's far more expensive than
```
        movl    G(caml_young_ptr), %eax
        subl    $8, %eax
        movl    %eax, G(caml_young_ptr)
```
that's done currently by single-core runtime. Why not to hold some pointers in SSE registers once i386 OCaml port does not use them anyway?

**Comment by kayceesrk** [comment]
@db4 Using SSE registers seems like an interesting idea. I hadn't actually looked at the i386 runtime. Looks like no runtime is cached in the registers it seems given the dearth of registers. Perhaps @stedolan will have more thoughts on this idea.

**Comment by bluddy** [comment]
Using SSE registers increases the cost of every program, since the OS needs to be informed about maintaining them and preserving them (ie. copying all of them) in context switches. I'm not sure what OCaml does with this right now (what setting it uses), but it is an interesting idea.

**Comment by db4** [comment]
> OS needs to be informed about maintaining them and preserving them (ie. copying all of them) in context switches

Really? I always thought it's done automatically at least by Linux and Windows (OS knows what registers have been used by a process and then saves them if necessary). Anyway, the cost won't be higher than for amd64 where SSE registers are used for floating point operations.

**Comment by bluddy** [comment]
OK, looks like [context switching isn't really much of an issue](https://tthtlc.wordpress.com/2016/12/17/understanding-fpu-usage-in-linux-kernel/), and it's done efficiently with hardware support. Good to know.
