### ISSUE TITLE
Use TSX for rewriting remembered set at the end of minor GC

### ISSUE THREAD

**Issue by kayceesrk** [ocaml-multicore/ocaml-multicore#94]
At the end of a minor collection, the remembered set of major to minor references are rewritten [0]. This rewrite races with other domains which might legitimately overwrite the field. In order to erroneously overwrite such a legitimate write by a different domain, the rewrite has to be performed through a compare-and-swap. The operation checks whether the major heap reference still points to the minor heap object. If so, the reference is atomically rewritten to point to the new location on the minor heap object in the major heap. Importantly, if this CAS fails, then it indicates that some other domain has updated the field. In this case, the rewrite is aborted. 

The trouble is that CAS is an expensive operation due to the full memory fence associated with each CAS. In this particular use case, we need the atomicity of CAS but not the memory fence. Intel's Transactional Synchronization Extensions (TSX) provides the necessary abstraction. TSX provides a limited hardware transactional memory abstraction. At its core, TSX provides two instructions `xbegin fallback` and `xend` which are used to describe start and end of transactional regions. If the whole region could be executed atomically without interference from other threads, the transaction succeeds. Otherwise, any changes performed within the transactional region is discarded and the code jumps to `fallback` address. The transactions might fail not just due to interference from other concurrent threads, but also due to variety of reasons including exhausting of hardware buffers for transactions, interrupts, etc. Importantly, TSX only involves a single memory fence for the entire transaction.

The proposal is to break the remembered set rewrite loop into multiple chunks where the rewrite is first attempted with TSX and on failure attempt the chunk using CAS.

[0] https://github.com/ocamllabs/ocaml-multicore/blob/master/byterun/minor_gc.c#L371-L381

**Comment by kayceesrk** [comment]
Closing due to https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=c2955f270a84762343000f103e0640d29c7a96f3.

**Comment by bluddy** [comment]
I guess the dream of doing transactional memory in hardware is dead?
