### ISSUE TITLE
Implement compaction

### ISSUE THREAD

**Issue by kayceesrk** [ocaml-multicore/ocaml-multicore#99]
Currently the multicore GC does not support compaction. A reasonable approach might be to perform stop-the-world compaction at the end of major GC.

**Comment by vladdy** [comment]
Is this still still actual? If it is, can somebody with a little of OCaml knowledge still help with this?

**Comment by kayceesrk** [comment]
Hi @vladdy, the plans have evolved since the original issue was made. We're not going to pursue compaction for OCaml 5.0 MVP. Hence, I'm going to close this issue. Apologies for keeping it open.

To answer your technical question, knowledge of OCaml is not critical to work on this issue. The changes are mostly in the C runtime. But a good working knowledge of the (Multicore) OCaml runtime is necessary for this.

Another point I should mention here is that we're currently looking at the idea of using the best-fit allocator from stock OCaml and adapt it to multicore. I would think that it would be reasonable to look at this issue, if at all, only after the allocator design is resolved.
